version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp"
      androidx:
        patterns:
          - "androidx.*"
          - "com.android.*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
